version: '2'

services:
  couchbasedb:
    build: ./docker/couchbase
    container_name: bitdistrict-couchbase
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=travel-sample
      - COUCHBASE_BUCKET_PASSWORD=
    ports:
     - 28091:8091
     - 28092:8092
     - 28093:8093
     - 28094:8094
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: bitdistrict-nodejs
    command: /docker-setup.sh
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - couchbasedb
    depends_on:
      - couchbasedb
    ports:
      - 3000:3000
      - 56745:56745 #debug port
