version: '3'

services:
  postgresdb:
    image: "postgres:15.3-alpine"
    environment:
      POSTGRES_USER: mkpremium_local_user
      POSTGRES_PASSWORD: mkpremium_local_password
      POSTGRES_DB: mkpremium
    ports:
      - "5432:5432"
