version: '3'

services:
  postgresdb:
    image: "postgres:15.3-alpine"
    environment:
      POSTGRES_USER: mkpremium_local_user
      POSTGRES_PASSWORD: mkpremium_local_password
      POSTGRES_DB: mkpremium
    ports:
      - "5432:5432"


  couchbasedb:
    image: "couchbase:community-6.6.0"

    ports:
      - "8091:8091" # REST/HTTP including Web UI
      - "8092:8092" # Views and XDCR access
      - "8093:8093" # Query service REST/HTTP traffic
      - "8094:8094" # Search service REST/HTTP traffic
      - "11210:11210" # Data Service

#    ulimits:
#      nofile: 40960
#      core: 100000000
#      memlock: 100000000

#  sqs:
#    image: juanformoso/moto_docker
#    ports:
#      - "5000:5000"
#    environment:
#      - SQS_INIT_QUEUES=events
#    image: roribio16/alpine-sqs
#    ports:
#      - "9324:9324"
#      - "9325:9325"
#    volumes:
#      - ./docker/elasticmq.conf:/opt/config/elasticmq.conf

#    image: localstack/localstack
#    privileged: true
#    environment:
#      - SERVICES=SQS
#      - DEBUG=1
#      - DATA_DIR=/tmp/localstack/data
#      - PORT_WEB_UI=8081
#    ports:
#      - "4576:4576"
#      - "8081:8081"
#    volumes:
#      - "./tmp/localstack:/tmp/localstack"
