version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: mk-backend:local

    restart: on-failure
    environment:
      COUCHBASE_URI: "couchbase://couchbasedb?detailed_errcodes=1"
    expose:
      - "9001"
    ports:
      - "9001:9001"
    volumes:
      - ./docker/wait-for-it.sh:/tmp/wait-for-it.sh
    links:
      - couchbasedb
    depends_on:
      - couchbasedb
    entrypoint: ["/tmp/wait-for-it.sh", "couchbase_db:8091", "--", "node", "/app/bin/www.js"]

  couchbasedb:
    image: "couchbase:community-6.6.0"

    ports:
      - "8091:8091" # REST/HTTP including Web UI
      - "8092:8092" # Views and XDCR access
      - "8093:8093" # Query service REST/HTTP traffic
      - "8094:8094" # Search service REST/HTTP traffic
      - "11210:11210" # Data Service

    ulimits:
      nofile: 40960
      core: 100000000
      memlock: 100000000

#  localstack:
#    image: localstack/localstack
#    ports:
#      - "4567-4584:4567-4584"
#      - "8080:8080" # web UI
#    environment:
#      - SERVICES=sqs
