version: '3'

networks:
  mkpremium:
    external: false

services:
  couchbase:
      build: ~/docker/couchbase
      restart: always
      networks:
        - mkpremium
      ports:
        - "8091:8091"
        - "8092:8092"
        - "8093:8093"
        - "9110:9110"
        - "11207:11207"
        - "11210:11210"
        - "11211:11211"
        - "18091:18091"
        - "18092:18092"
      volumes:
        - ./couchbase/data:/opt/couchbase/var
      environment:
        - COUCHBASE_USER=mk_administrator
        - COUCHBASE_PASS=oov,im3aish\ei7uphac7EiR
        - COUCHBASE_CLUSTER_RAM_SIZE=5120
        - COUCHBASE_BUCKET_RAM_SIZE=4096
        - COUCHBASE_BUCKET=mkpremium
