export enum ContactType {
  PRINCIPAL = 'PRINCIPAL',
  SECUNDARIO = 'SECUNDARIO',
  MISMA_CASA = 'MISMA CASA',
  HERMANOS = 'HERMANOS',
  HIJOS = 'HIJOS',
  FAMILIAR = 'FAMILIAR',
  VECINO = 'VECINO',
  NINGUNO = 'NINGUNO'
}
