# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.1
      - image: rkmax/couchbase:bitdistrict

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Wait for couchbase
          command: dockerize -wait tcp://localhost:8091 -timeout 1m

      - run:
          name: Install dependencies
          command: npm install

      # run tests!
      - run:
          name: Running testing
          command: NODE_ENV=test npm test -- --reporter mocha-circleci-reporter

      - run:
          name: Testing build
          command: npm run build

      - store_artifacts:
          path: ~/test-results/junit.xml
          prefix: test

      - store_test_results:
          path: junit.xml

workflows:
  version: 2
  build:
    jobs:
      - test
