# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:carbon
      - image: rkmax/couchbase:bitdistrict

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Wait for couchbase
          command: dockerize -wait tcp://localhost:8091 -timeout 1m

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Firebase setup
          command: >-
              sudo apt-get update && sudo apt-get install -y python-dev &&
              curl -O https://bootstrap.pypa.io/get-pip.py &&
              sudo python get-pip.py &&
              sudo pip install awscli --upgrade &&
              aws s3 cp --region eu-west-3 s3://mkpremium/config/firebaseComerciales.json firebaseComerciales.json &&
              aws s3 cp --region eu-west-3 s3://mkpremium/config/firebaseInformadores.json firebaseInformadores.json

      # run tests!
      - run:
          name: Running testing
          command: NODE_ENV=test npm test -- --reporter mocha-circleci-reporter

      - run:
          name: Testing build
          command: npm run build

      - store_artifacts:
          path: ~/test-results/junit.xml
          prefix: test

      - store_test_results:
          path: junit.xml

  deploy:
    docker:
      - image: circleci/node:9.2
    environment:
      - NODE_ENV: "production"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys

      - run:
          name: Firebase setup
          command: >-
              sudo apt-get update && sudo apt-get install -y python-dev &&
              curl -O https://bootstrap.pypa.io/get-pip.py &&
              sudo python get-pip.py &&
              sudo pip install awscli --upgrade &&
              aws s3 cp --region eu-west-3 s3://mkpremium/config/firebaseComerciales.json firebaseComerciales.json &&
              aws s3 cp --region eu-west-3 s3://mkpremium/config/firebaseInformadores.json firebaseInformadores.json

      - run:
          name: PM2 Setup
          command: aws s3 cp --region eu-west-3 s3://mkpremium/config/dev/mkpremium-pm2.json mkpremium-pm2.json

      - run:
          name: install deps
          command: sudo apt install -y rsync

      - run:
          name: Adding deploy host keys to known hosts
          command: ssh-keyscan -H ec2-34-248-103-55.eu-west-1.compute.amazonaws.com >>  ~/.ssh/known_hosts

      - run:
          name: Building & Deploying Files
          command: TERM=xterm npm run deploy -- centos@ec2-34-248-103-55.eu-west-1.compute.amazonaws.com mkpremium

workflows:
  version: 2
  # testing is done on any branch that is not master
  testing:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  # Deployment should happen just on master branch
  deploying:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
