# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:carbon
      - image: rkmax/couchbase:bitdistrict
    environment:
      - NODE_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Wait for couchbase
          command: dockerize -wait tcp://localhost:8091 -timeout 1m

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Running testing
          command: MOCHA_FILE=~/test-results/junit.xml npm test -- --reporter mocha-circleci-reporter

      - run:
          name: Testing build
          command: npm run build

      - store_artifacts:
          path: ~/test-results/

      - store_test_results:
          path: ~/test-results/

  deploy:
    docker:
      - image: circleci/node:9.2
    environment:
      - NODE_ENV: "production"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys

      - run:
          name: Adding deploy host keys to known hosts
          command: ssh-keyscan -H ec2-34-248-103-55.eu-west-1.compute.amazonaws.com >>  ~/.ssh/known_hosts

      - run:
          name: Building & Deploying Files
          command: npm run deploy -- ec2-34-248-103-55.eu-west-1.compute.amazonaws.com mkpremium

workflows:
  version: 2
  # testing is done on any branch that is not master
  testing:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  # Deployment should happen just on master branch
  deploying:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
