upstream mkpremium_app {
  server 127.0.0.1:9001;
}

server {
    listen 80 default;
    listen [::]:80 default;

    server_name _;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name _;

    ssl_certificate /etc/nginx/certs/live/demomk.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/demomk.com/privkey.pem;

    location ~ ^/(operators|owners|worksheets|docs) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_pass http://mkpremium_app;

    }

    location / {
      root /sites/mkpremium;
      index index.html;
      try_files $uri $uri/ /index.html =404;
    }
}
