version: '3'

networks:
  mkpremium:
    external: false

services:
  queue:
    image: "artefactual/gearmand"
    ports:
      - "4730:4730"
    networks:
      - mkpremium
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./web/data/conf:/etc/nginx/conf.d
      - ./web/data/cache:/cache
      - ./web/data/certs:/certs
      - ./web/data/site:/site
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mkpremium
    depends_on:
      - application
