#!/usr/bin/env bash

set -e

echo "Ensuring that couchbase-server is running"
sv start couchbase-server || exit 1

cd `dirname $0`

echo "Starting to wait"
exec ./wait-for-it.sh  "localhost:8091" -- ./init-couchbase.sh
