version: '3'

services:
  web:
    network_mode: "host"
    volumes:
      - ~/sites:/sites
      - ~/nginx-certs:/etc/nginx/certs
    restart: always
    image: "rkmax/nginx:bitdistrict-2"
    ports:
      - "80:80"
      - "443:443"

#volumes:
#  nginx-certs:
#    external: true
