on:
  push:
    branches:
      - main

name: Deploy to Amazon ECS

env:
  IMAGE_URL: 173249668334.dkr.ecr.eu-west-1.amazonaws.com/backend:${{ github.sha }}

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    services:
      couchbase_db:
        image: "couchbase:community-6.6.0"
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 11210:11210

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & Lint
        run: |
          npm install
          npm run lint

      - name: Prepare Couchbase
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 5
          retry_wait_seconds: 30
          command: npx ts-node scripts/couchbase/init-db.js

      - name: Test
        run: |
          npm run test
          npm run test:e2e

      - name: Extract Couchbase logs
        if: failure()
        run: docker cp `docker ps --format '{{.Names}}'`:/opt/couchbase/var/lib/couchbase/logs couchbase_logs
      - name: Upload Couchbase logs artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: couchbase_logs
          path: couchbase_logs

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build, test ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Render Amazon ECS task definition for API container
        id: api-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infrastructure/ecs/api-task-definition.json
          container-name: api
          image: ${{ env.IMAGE_URL }}

      - name: Deploy Amazon ECS API task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.api-task-def.outputs.task-definition }}
          service: api
          cluster: production
          wait-for-minutes: 5

      - name: Render Amazon ECS task definition for websocket container
        id: websocket-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infrastructure/ecs/websocket-task-definition.json
          container-name: websocket
          image: ${{ env.IMAGE_URL }}

      - name: Deploy Amazon ECS WebSocket task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.websocket-task-def.outputs.task-definition }}
          service: websocket
          cluster: production
          wait-for-minutes: 5

      - name: Render Amazon ECS task definition for cronjobs container
        id: cronjobs-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infrastructure/ecs/cronjobs-task-definition.json
          container-name: cronjobs
          image: ${{ env.IMAGE_URL }}

      - name: Deploy Amazon ECS cronjobs task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.cronjobs-task-def.outputs.task-definition }}
          cluster: production
          wait-for-minutes: 5

